version: '3.8'

networks:
  app_network:
    external: true # Ein vorhandenes Netzwerk nutzen (z. B. das der Datenbank)

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/chat_app
      - /chat_app/node_modules
    working_dir: /chat_app
    environment:
      - NODE_ENV=development
      - PGHOST=my-postgres
      - PGUSER=postgres
      - PGPASSWORD=webpdatenbank
      - PGDATABASE=chatapp
      - PGPORT=5432
    networks:
      - app_network
    command: npm run dev
